# Generated by Django 4.2.7 on 2026-06-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_karat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_weight',
            field=models.BooleanField(default=True, verbose_name='Show Weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
